[2024-02-16T16:49:17.354+0900] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CollectNaverNews.news_Content_Comment_Collect manual__2024-02-16T04:34:59.660831+00:00 [queued]>
[2024-02-16T16:49:17.361+0900] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CollectNaverNews.news_Content_Comment_Collect manual__2024-02-16T04:34:59.660831+00:00 [queued]>
[2024-02-16T16:49:17.362+0900] {taskinstance.py:2170} INFO - Starting attempt 5 of 1
[2024-02-16T16:49:17.541+0900] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): news_Content_Comment_Collect> on 2024-02-16 04:34:59.660831+00:00
[2024-02-16T16:49:17.548+0900] {standard_task_runner.py:60} INFO - Started process 201899 to run task
[2024-02-16T16:49:17.552+0900] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'CollectNaverNews', 'news_Content_Comment_Collect', 'manual__2024-02-16T04:34:59.660831+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/Naver_News_Collect.py', '--cfg-path', '/tmp/tmpued6mrbj']
[2024-02-16T16:49:17.555+0900] {standard_task_runner.py:88} INFO - Job 39: Subtask news_Content_Comment_Collect
[2024-02-16T16:49:17.596+0900] {task_command.py:423} INFO - Running <TaskInstance: CollectNaverNews.news_Content_Comment_Collect manual__2024-02-16T04:34:59.660831+00:00 [running]> on host ip-172-31-11-88.ap-northeast-2.compute.internal
[2024-02-16T16:49:17.662+0900] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='CollectNaverNews' AIRFLOW_CTX_TASK_ID='news_Content_Comment_Collect' AIRFLOW_CTX_EXECUTION_DATE='2024-02-16T04:34:59.660831+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-16T04:34:59.660831+00:00'
[2024-02-16T16:49:17.677+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-02-16T16:49:17.769+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-02-16T16:49:17.857+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-02-16T16:49:17.942+0900] {logger.py:11} INFO - Driver [/home/ubuntu/.wdm/drivers/chromedriver/linux64/121.0.6167.85/chromedriver-linux64/chromedriver] found in cache
[2024-02-16T16:49:18.630+0900] {Naver_News_Collect.py:118} INFO - 접속완료
[2024-02-16T16:49:48.724+0900] {Naver_News_Collect.py:121} INFO - 0 Start
[2024-02-16T16:49:58.823+0900] {Naver_News_Collect.py:157} INFO - 0 End
[2024-02-16T16:50:01.827+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-02-16T16:50:01.920+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-02-16T16:50:02.006+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-02-16T16:50:02.089+0900] {logger.py:11} INFO - Driver [/home/ubuntu/.wdm/drivers/chromedriver/linux64/121.0.6167.85/chromedriver-linux64/chromedriver] found in cache
[2024-02-16T16:50:02.774+0900] {Naver_News_Collect.py:118} INFO - 접속완료
[2024-02-16T16:50:03.887+0900] {Naver_News_Collect.py:121} INFO - 0 Start
[2024-02-16T16:50:16.228+0900] {Naver_News_Collect.py:157} INFO - 1 End
[2024-02-16T16:50:19.232+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-02-16T16:50:19.325+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-02-16T16:50:19.409+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-02-16T16:50:19.497+0900] {logger.py:11} INFO - Driver [/home/ubuntu/.wdm/drivers/chromedriver/linux64/121.0.6167.85/chromedriver-linux64/chromedriver] found in cache
[2024-02-16T16:50:20.198+0900] {Naver_News_Collect.py:118} INFO - 접속완료
[2024-02-16T16:50:21.311+0900] {Naver_News_Collect.py:121} INFO - 1 Start
[2024-02-16T16:50:44.006+0900] {Naver_News_Collect.py:157} INFO - 2 End
[2024-02-16T16:50:47.010+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-02-16T16:50:47.102+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-02-16T16:50:47.185+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-02-16T16:50:47.267+0900] {logger.py:11} INFO - Driver [/home/ubuntu/.wdm/drivers/chromedriver/linux64/121.0.6167.85/chromedriver-linux64/chromedriver] found in cache
[2024-02-16T16:50:47.949+0900] {Naver_News_Collect.py:118} INFO - 접속완료
[2024-02-16T16:50:49.130+0900] {Naver_News_Collect.py:121} INFO - 2 Start
[2024-02-16T16:51:12.103+0900] {Naver_News_Collect.py:157} INFO - 3 End
[2024-02-16T16:51:14.106+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-02-16T16:51:14.198+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-02-16T16:51:14.287+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-02-16T16:51:14.371+0900] {logger.py:11} INFO - Driver [/home/ubuntu/.wdm/drivers/chromedriver/linux64/121.0.6167.85/chromedriver-linux64/chromedriver] found in cache
[2024-02-16T16:51:15.050+0900] {Naver_News_Collect.py:118} INFO - 접속완료
[2024-02-16T16:51:16.114+0900] {Naver_News_Collect.py:121} INFO - 3 Start
[2024-02-16T16:51:29.012+0900] {Naver_News_Collect.py:157} INFO - 4 End
[2024-02-16T16:51:31.711+0900] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 201899. PIDs of all processes in the group: [201899]
[2024-02-16T16:51:31.712+0900] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 201899
[2024-02-16T16:51:31.712+0900] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-16T16:51:31.718+0900] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/Naver_News_Collect.py", line 158, in news_Content_Comment_Collect
    time.sleep(random.randint(2,3))
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-02-16T16:51:31.720+0900] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=CollectNaverNews, task_id=news_Content_Comment_Collect, execution_date=20240216T043459, start_date=20240216T074917, end_date=20240216T075131
[2024-02-16T16:51:31.734+0900] {standard_task_runner.py:107} ERROR - Failed to execute job 39 for task news_Content_Comment_Collect (Task received SIGTERM signal; 201899)
[2024-02-16T16:51:31.765+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=201899, status='terminated', exitcode=1, started='07:49:17') (201899) terminated with exit code 1
